name = "ClassInt"
uuid = "cb7c3c70-0ee2-4675-be37-174a39ad7e4c"
authors = ["M Leonawicz <mfleonawicz@gmail.com>"]
version = "0.1.0"

[deps]
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Clustering = "0.15"
StatsBase = "0.34"
julia = "1.6" 